import type {
  AchievementDef, Lang, NodeDef, NodeTypeId, ResourceId, TechDef, TechId, UpgradeDef, UpgradeId,
} from './types';

const D = 'data'; // key alias (kept short on purpose)

// ── Resources ────────────────────────────────────────────────────────────────

export const RES_META: Record<ResourceId, { color: string; nameKey: string }> = {
  [D]:       { color: '#3fc1ff', nameKey: 'res.data' },
  compute:   { color: '#ffb02e', nameKey: 'res.compute' },
  processed: { color: '#4fe3c1', nameKey: 'res.processed' },
  filtered:  { color: '#8fb7ff', nameKey: 'res.filtered' },
  encrypted: { color: '#c792ff', nameKey: 'res.encrypted' },
  fragment:  { color: '#45e08c', nameKey: 'res.fragment' },
  credits:   { color: '#ffd24a', nameKey: 'res.credits' },
  signal:    { color: '#ff8a5c', nameKey: 'res.signal' },
};

export const RES_ORDER: ResourceId[] = [D, 'compute', 'processed', 'filtered', 'encrypted', 'fragment', 'credits', 'signal'];

// ── Tuning constants ─────────────────────────────────────────────────────────

export const TUNE = {
  travelTime: 1.15,
  baseRate: 2.0,
  bwMultPerLevel: 1.5,
  storageDrainMax: 0.9,   // reserve conversion at 100% fill (slower, buffer stays visible)
  storageDrainExp: 1.3,   // drain ∝ fill^exp  → fuller = faster
  capPerLevel: 0.5,
  speedPerLevel: 0.88,
  nodeTimePerLevel: 0.85,
  nodeQtyPerLevel: 0.25,
  nodeMaxLevel: 5,
  offlineCapHours: 8,
  offlineEfficiency: 0.5,
  autosaveSec: 5,
};

// ── Endless progression configs ──────────────────────────────────────────────

export const SURGE_CFG = { intervalMin: 40, intervalMax: 90, window: 8, active: 15, mult: 3 };
export const TIER_CFG = { base: 150, growth: 5, bonusPerTier: 0.10 };
export const LEGACY_CFG = { divisor: 10, multPerPoint: 0.02, costScale: 1.2, startDataBonus: 0.25 };
export const RESEARCH_CFG = { base: 300, growth: 2.5, bonusPerTier: 0.08 };
export const TECH_LATE_MULT = 3;
// каждая открытая технология удорожает следующую на 50% — растягивает поздний темп
export const TECH_COST_SCALE = 1.5;
export const MILESTONES = [25, 50, 75];

export function tierGoal(tier: number): number {
  return Math.round(TIER_CFG.base * Math.pow(TIER_CFG.growth, tier));
}

// ── Node definitions (data-driven) ───────────────────────────────────────────

export const NODE_DEFS: Record<NodeTypeId, NodeDef> = {
  relay: {
    id: 'relay', nameKey: 'nd.relay', descKey: 'nd.relay.d',
    category: 'generator', cost: { [D]: 25 }, costGrowth: 1.12,
    inputs: [], outputs: [D],
    recipe: { inputs: [], outputs: [{ resource: D, amount: 1 }], time: 2.2 },
    capacity: 20,
  },
  storage: {
    id: 'storage', nameKey: 'nd.storage', descKey: 'nd.storage.d',
    category: 'storage', cost: { [D]: 60 }, costGrowth: 1.15,
    inputs: [D], outputs: [D],
    capacity: 120,
  },
  cache: {
    id: 'cache', nameKey: 'nd.cache', descKey: 'nd.cache.d',
    category: 'transfer', cost: { [D]: 45 }, costGrowth: 1.15,
    inputs: [D], outputs: [D],
    capacity: 40,
  },
  compute: {
    id: 'compute', nameKey: 'nd.compute', descKey: 'nd.compute.d',
    category: 'generator', cost: { [D]: 140 }, costGrowth: 1.15,
    inputs: [], outputs: ['compute'],
    recipe: { inputs: [], outputs: [{ resource: 'compute', amount: 1 }], time: 4 },
    capacity: 15,
  },
  router: {
    id: 'router', nameKey: 'nd.router', descKey: 'nd.router.d',
    category: 'transfer', cost: { [D]: 120 }, costGrowth: 1.18,
    inputs: [D, D], outputs: [D, D],
    capacity: 12,
  },
  balancer: {
    id: 'balancer', nameKey: 'nd.balancer', descKey: 'nd.balancer.d',
    category: 'transfer', cost: { [D]: 900 }, costGrowth: 1.22,
    inputs: [D, D], outputs: [D, D, D, D],
    capacity: 60, tech: 'routing',
  },
  proxy: {
    id: 'proxy', nameKey: 'nd.proxy', descKey: 'nd.proxy.d',
    category: 'processor', cost: { [D]: 350 }, costGrowth: 1.2,
    inputs: [D], outputs: ['processed'],
    recipe: { inputs: [{ resource: D, amount: 2 }], outputs: [{ resource: 'processed', amount: 1 }], time: 2.8 },
    capacity: 10, tech: 'routing',
  },
  processor: {
    id: 'processor', nameKey: 'nd.processor', descKey: 'nd.processor.d',
    category: 'processor', cost: { [D]: 600 }, costGrowth: 1.22,
    inputs: [D, 'compute'], outputs: [],
    recipe: {
      inputs: [{ resource: D, amount: 2 }, { resource: 'compute', amount: 1 }],
      outputs: [{ resource: 'fragment', amount: 1 }], time: 5,
    },
    capacity: 10, tech: 'processing',
  },
  archive: {
    id: 'archive', nameKey: 'nd.archive', descKey: 'nd.archive.d',
    category: 'processor', cost: { [D]: 500 }, costGrowth: 1.22,
    inputs: [D], outputs: [],
    recipe: { inputs: [{ resource: D, amount: 4 }], outputs: [{ resource: 'credits', amount: 2 }], time: 4.5 },
    capacity: 12, tech: 'processing',
  },
  firewall: {
    id: 'firewall', nameKey: 'nd.firewall', descKey: 'nd.firewall.d',
    category: 'processor', cost: { [D]: 1200 }, costGrowth: 1.22,
    inputs: [D], outputs: ['filtered'],
    recipe: { inputs: [{ resource: D, amount: 3 }], outputs: [{ resource: 'filtered', amount: 2 }], time: 3 },
    capacity: 10, tech: 'security',
  },
  encryption: {
    id: 'encryption', nameKey: 'nd.encryption', descKey: 'nd.encryption.d',
    category: 'processor', cost: { [D]: 2200 }, costGrowth: 1.25,
    inputs: ['filtered', 'compute'], outputs: ['encrypted'],
    recipe: {
      inputs: [{ resource: 'filtered', amount: 2 }, { resource: 'compute', amount: 1 }],
      outputs: [{ resource: 'encrypted', amount: 1 }], time: 4,
    },
    capacity: 8, tech: 'encryptionTech',
  },
  refinery: {
    id: 'refinery', nameKey: 'nd.refinery', descKey: 'nd.refinery.d',
    category: 'processor', cost: { credits: 380 }, costGrowth: 1.3,
    inputs: ['processed', 'filtered'], outputs: [],
    recipe: {
      inputs: [{ resource: 'processed', amount: 1 }, { resource: 'filtered', amount: 1 }],
      outputs: [{ resource: 'fragment', amount: 1 }], time: 5,
    },
    capacity: 8, tech: 'distributed',
  },
  datacenter: {
    id: 'datacenter', nameKey: 'nd.datacenter', descKey: 'nd.datacenter.d',
    category: 'processor', cost: { [D]: 4500 }, costGrowth: 1.3,
    inputs: ['processed', 'encrypted', 'compute'], outputs: [],
    recipe: {
      inputs: [
        { resource: 'processed', amount: 1 }, { resource: 'encrypted', amount: 1 },
        { resource: 'compute', amount: 2 },
      ],
      outputs: [{ resource: 'credits', amount: 5 }], time: 6,
    },
    capacity: 8, tech: 'distributed',
  },
  hub: {
    id: 'hub', nameKey: 'nd.hub', descKey: 'nd.hub.d',
    category: 'transfer', cost: { credits: 260 }, costGrowth: 1.3,
    inputs: [D, D, D, D],
    outputs: [D, D, D, D],
    capacity: 24, tech: 'distributed',
  },
  core: {
    id: 'core', nameKey: 'nd.core', descKey: 'nd.core.d',
    category: 'processor', cost: { credits: 8000 }, costGrowth: 1.5,
    inputs: [D, 'compute'], outputs: [],
    recipe: {
      inputs: [{ resource: D, amount: 5 }, { resource: 'compute', amount: 2 }],
      outputs: [{ resource: 'credits', amount: 8 }], time: 3,
    },
    capacity: 20, requireCore: true,
  },
  // ── Волна сырья: сенсоры → сигнал → анализ (Path A / телеметрия) ──
  sensor: {
    id: 'sensor', nameKey: 'nd.sensor', descKey: 'nd.sensor.d',
    category: 'generator', cost: { credits: 160 }, costGrowth: 1.2,
    inputs: [], outputs: ['signal'],
    recipe: { inputs: [], outputs: [{ resource: 'signal', amount: 1 }], time: 2.2 },
    capacity: 15, tech: 'telemetry',
  },
  signalbuffer: {
    id: 'signalbuffer', nameKey: 'nd.signalbuffer', descKey: 'nd.signalbuffer.d',
    category: 'storage', cost: { credits: 110 }, costGrowth: 1.2,
    inputs: ['signal'], outputs: ['signal'],
    capacity: 24, tech: 'telemetry',
  },
  analyzer: {
    id: 'analyzer', nameKey: 'nd.analyzer', descKey: 'nd.analyzer.d',
    category: 'processor', cost: { credits: 420 }, costGrowth: 1.25,
    inputs: ['signal', 'compute'], outputs: [],
    recipe: {
      inputs: [{ resource: 'signal', amount: 2 }, { resource: 'compute', amount: 1 }],
      outputs: [{ resource: 'fragment', amount: 1 }], time: 4.5,
    },
    capacity: 8, tech: 'telemetry',
  },
  // ── Хранилище вычислений (Path A) ──
  computebank: {
    id: 'computebank', nameKey: 'nd.computebank', descKey: 'nd.computebank.d',
    category: 'storage', cost: { [D]: 400 }, costGrowth: 1.18,
    inputs: ['compute'], outputs: ['compute'],
    capacity: 24, tech: 'processing',
  },
  // ── Продвинутая маршрутизация (база) ──
  smartrouter: {
    id: 'smartrouter', nameKey: 'nd.smartrouter', descKey: 'nd.smartrouter.d',
    category: 'transfer', cost: { [D]: 420 }, costGrowth: 1.2,
    inputs: [D, D, D], outputs: [D, D, D],
    capacity: 18, tech: 'routing',
  },
  // ── Кредитные процессоры (Path B / Path A) ──
  compressor: {
    id: 'compressor', nameKey: 'nd.compressor', descKey: 'nd.compressor.d',
    category: 'processor', cost: { [D]: 1500 }, costGrowth: 1.25,
    inputs: ['processed', D], outputs: [],
    recipe: {
      inputs: [{ resource: 'processed', amount: 1 }, { resource: D, amount: 2 }],
      outputs: [{ resource: 'credits', amount: 3 }], time: 5,
    },
    capacity: 8, tech: 'security',
  },
  assembler: {
    id: 'assembler', nameKey: 'nd.assembler', descKey: 'nd.assembler.d',
    category: 'processor', cost: { credits: 600 }, costGrowth: 1.28,
    inputs: ['encrypted', 'processed'], outputs: [],
    recipe: {
      inputs: [{ resource: 'encrypted', amount: 1 }, { resource: 'processed', amount: 1 }],
      outputs: [{ resource: 'fragment', amount: 1 }], time: 5,
    },
    capacity: 8, tech: 'encryptionTech',
  },
  forge: {
    id: 'forge', nameKey: 'nd.forge', descKey: 'nd.forge.d',
    category: 'processor', cost: { credits: 1100 }, costGrowth: 1.3,
    inputs: ['encrypted', 'compute'], outputs: [],
    recipe: {
      inputs: [{ resource: 'encrypted', amount: 1 }, { resource: 'compute', amount: 2 }],
      outputs: [{ resource: 'credits', amount: 4 }], time: 5,
    },
    capacity: 8, tech: 'distributed',
  },
};

export const SHOP_ORDER: NodeTypeId[] = [
  'relay', 'sensor', 'storage', 'cache', 'computebank', 'signalbuffer',
  'compute', 'router', 'smartrouter', 'balancer', 'proxy', 'processor', 'analyzer',
  'archive', 'firewall', 'compressor', 'encryption', 'assembler', 'forge',
  'refinery', 'datacenter', 'hub', 'core',
];

export const CATEGORY_ORDER: NodeDef['category'][] = ['generator', 'storage', 'transfer', 'processor'];

// ── Technologies (branched after routing) ────────────────────────────────────

export const TECH_DEFS: TechDef[] = [
  { id: 'routing',        nameKey: 'tc.routing',        descKey: 'tc.routing.d',        cost: { [D]: 150 },  unlocks: ['proxy', 'balancer', 'smartrouter'] },
  { id: 'processing',     nameKey: 'tc.processing',     descKey: 'tc.processing.d',     cost: { [D]: 300 },  unlocks: ['processor', 'archive', 'computebank'], requires: 'routing', path: 'A' },
  { id: 'telemetry',      nameKey: 'tc.telemetry',      descKey: 'tc.telemetry.d',      cost: { [D]: 450 },  unlocks: ['sensor', 'signalbuffer', 'analyzer'], requires: 'processing', path: 'A' },
  { id: 'security',       nameKey: 'tc.security',       descKey: 'tc.security.d',       cost: { [D]: 500 },  unlocks: ['firewall', 'compressor'], requires: 'routing', path: 'B' },
  { id: 'encryptionTech', nameKey: 'tc.encryptionTech', descKey: 'tc.encryptionTech.d', cost: { [D]: 800 },  unlocks: ['encryption', 'assembler'], requires: 'security', path: 'B' },
  { id: 'distributed',    nameKey: 'tc.distributed',    descKey: 'tc.distributed.d',    cost: { [D]: 1200 }, unlocks: ['datacenter', 'hub', 'refinery', 'forge'], requires: 'processing', path: 'A' },
];

// ── Global upgrades (endless) ────────────────────────────────────────────────

export const UPGRADE_DEFS: UpgradeDef[] = [
  {
    id: 'bandwidth', nameKey: 'up.bandwidth', descKey: 'up.bandwidth.d', max: Infinity,
    cost: (l) => l < 3 ? { [D]: Math.round(150 * Math.pow(2.2, l)) } : { credits: Math.round(15 * Math.pow(1.9, l - 3)) },
  },
  {
    id: 'storageCap', nameKey: 'up.storageCap', descKey: 'up.storageCap.d', max: Infinity,
    cost: (l) => ({ [D]: Math.round(200 * Math.pow(2.1, l)) }),
  },
  {
    id: 'prodSpeed', nameKey: 'up.prodSpeed', descKey: 'up.prodSpeed.d', max: Infinity,
    cost: (l) => ({ [D]: Math.round(250 * Math.pow(2.2, l)) }),
  },
  {
    id: 'procSpeed', nameKey: 'up.procSpeed', descKey: 'up.procSpeed.d', max: Infinity,
    cost: (l) => ({ credits: Math.round(12 * Math.pow(1.9, l)) }),
  },
  {
    id: 'packetSize', nameKey: 'up.packetSize', descKey: 'up.packetSize.d', max: Infinity,
    cost: (l) => ({ credits: Math.round(15 * Math.pow(2.1, l)) }),
  },
];

// ── Achievements ─────────────────────────────────────────────────────────────

// Условия — декларативные (AchievementCondition). Новое достижение = новая строка здесь,
// без правки кода. Награды растут вместе со сложностью условия.
export const ACHIEVEMENTS: AchievementDef[] = [
  // ── Постройка конкретных узлов ──
  { id: 'relay3',      nameKey: 'ach.relay3',      descKey: 'ach.relay3.d',      condition: { type: 'nodeCount', nodeType: 'relay', count: 3 },       bonus: { kind: 'res', res: D, amount: 60 } },
  { id: 'relay8',      nameKey: 'ach.relay8',      descKey: 'ach.relay8.d',      condition: { type: 'nodeCount', nodeType: 'relay', count: 8 },       bonus: { kind: 'boost', target: 'gen', mult: 1.15, dur: 60 } },
  { id: 'storage3',    nameKey: 'ach.storage3',    descKey: 'ach.storage3.d',    condition: { type: 'nodeCount', nodeType: 'storage', count: 3 },     bonus: { kind: 'res', res: D, amount: 150 } },
  { id: 'router3',     nameKey: 'ach.router3',     descKey: 'ach.router3.d',     condition: { type: 'nodeCount', nodeType: 'router', count: 3 },      bonus: { kind: 'res', res: D, amount: 120 } },
  { id: 'compute3',    nameKey: 'ach.compute3',    descKey: 'ach.compute3.d',    condition: { type: 'nodeCount', nodeType: 'compute', count: 3 },     bonus: { kind: 'res', res: D, amount: 200 } },
  { id: 'processor3',  nameKey: 'ach.processor3',  descKey: 'ach.processor3.d',  condition: { type: 'nodeCount', nodeType: 'processor', count: 3 },   bonus: { kind: 'res', res: D, amount: 300 } },
  { id: 'processor8',  nameKey: 'ach.processor8',  descKey: 'ach.processor8.d',  condition: { type: 'nodeCount', nodeType: 'processor', count: 8 },   bonus: { kind: 'res', res: 'credits', amount: 50 } },
  { id: 'firewall3',   nameKey: 'ach.firewall3',   descKey: 'ach.firewall3.d',   condition: { type: 'nodeCount', nodeType: 'firewall', count: 3 },    bonus: { kind: 'res', res: 'credits', amount: 35 } },
  // ── Разнообразие сети ──
  { id: 'variety5',    nameKey: 'ach.variety5',    descKey: 'ach.variety5.d',    condition: { type: 'nodeTypeVariety', count: 5 },                    bonus: { kind: 'res', res: D, amount: 250 } },
  { id: 'variety8',    nameKey: 'ach.variety8',    descKey: 'ach.variety8.d',    condition: { type: 'nodeTypeVariety', count: 8 },                    bonus: { kind: 'boost', target: 'all', mult: 1.1, dur: 90 } },
  { id: 'variety12',   nameKey: 'ach.variety12',   descKey: 'ach.variety12.d',   condition: { type: 'nodeTypeVariety', count: 12 },                   bonus: { kind: 'res', res: 'credits', amount: 60 } },
  // ── Связи ──
  { id: 'conn5',       nameKey: 'ach.conn5',       descKey: 'ach.conn5.d',       condition: { type: 'connectionCount', count: 5 },                    bonus: { kind: 'res', res: D, amount: 80 } },
  { id: 'conn15',      nameKey: 'ach.conn15',      descKey: 'ach.conn15.d',      condition: { type: 'connectionCount', count: 15 },                   bonus: { kind: 'boost', target: 'all', mult: 1.05, dur: 90 } },
  { id: 'conn30',      nameKey: 'ach.conn30',      descKey: 'ach.conn30.d',      condition: { type: 'connectionCount', count: 30 },                   bonus: { kind: 'res', res: 'credits', amount: 45 } },
  // ── Длина цепочки ──
  { id: 'chain4',      nameKey: 'ach.chain4',      descKey: 'ach.chain4.d',      condition: { type: 'chainLength', length: 4 },                       bonus: { kind: 'boost', target: 'gen', mult: 1.1, dur: 60 } },
  { id: 'chain6',      nameKey: 'ach.chain6',      descKey: 'ach.chain6.d',      condition: { type: 'chainLength', length: 6 },                       bonus: { kind: 'res', res: 'credits', amount: 15 } },
  { id: 'chain10',     nameKey: 'ach.chain10',     descKey: 'ach.chain10.d',     condition: { type: 'chainLength', length: 10 },                      bonus: { kind: 'res', res: 'credits', amount: 60 } },
  // ── Ресурсы за забег / жизнь ──
  { id: 'credits50',   nameKey: 'ach.credits50',   descKey: 'ach.credits50.d',   condition: { type: 'statThreshold', stat: 'credits', value: 50 },    bonus: { kind: 'boost', target: 'proc', mult: 1.1, dur: 60 } },
  { id: 'credits500',  nameKey: 'ach.credits500',  descKey: 'ach.credits500.d',  condition: { type: 'statThreshold', stat: 'credits', value: 500 },   bonus: { kind: 'res', res: D, amount: 400 } },
  { id: 'credits2000', nameKey: 'ach.credits2000', descKey: 'ach.credits2000.d', condition: { type: 'statThreshold', stat: 'credits', value: 2000 },  bonus: { kind: 'boost', target: 'all', mult: 1.15, dur: 120 } },
  { id: 'frag10',      nameKey: 'ach.frag10',      descKey: 'ach.frag10.d',      condition: { type: 'statThreshold', stat: 'fragments', value: 10 },  bonus: { kind: 'boost', target: 'all', mult: 1.1, dur: 60 } },
  { id: 'frag50',      nameKey: 'ach.frag50',      descKey: 'ach.frag50.d',      condition: { type: 'statThreshold', stat: 'fragments', value: 50 },  bonus: { kind: 'res', res: 'credits', amount: 20 } },
  { id: 'frag200',     nameKey: 'ach.frag200',     descKey: 'ach.frag200.d',     condition: { type: 'statThreshold', stat: 'fragments', value: 200 }, bonus: { kind: 'res', res: 'credits', amount: 80 } },
  // ── Технологии и апгрейды ──
  { id: 'tech2',       nameKey: 'ach.tech2',       descKey: 'ach.tech2.d',       condition: { type: 'techCount', count: 2 },                          bonus: { kind: 'res', res: D, amount: 200 } },
  { id: 'tech5',       nameKey: 'ach.tech5',       descKey: 'ach.tech5.d',       condition: { type: 'techCount', count: 5 },                          bonus: { kind: 'res', res: 'credits', amount: 40 } },
  { id: 'upg3',        nameKey: 'ach.upg3',        descKey: 'ach.upg3.d',        condition: { type: 'statThreshold', stat: 'upgrades', value: 3 },    bonus: { kind: 'boost', target: 'proc', mult: 1.1, dur: 90 } },
  { id: 'upg10',       nameKey: 'ach.upg10',       descKey: 'ach.upg10.d',       condition: { type: 'statThreshold', stat: 'upgrades', value: 10 },   bonus: { kind: 'boost', target: 'proc', mult: 1.15, dur: 120 } },
  // ── Время в сессии ──
  { id: 'time5',       nameKey: 'ach.time5',       descKey: 'ach.time5.d',       condition: { type: 'statThreshold', stat: 'time', value: 300 },      bonus: { kind: 'boost', target: 'gen', mult: 1.1, dur: 120 } },
  { id: 'time20',      nameKey: 'ach.time20',      descKey: 'ach.time20.d',      condition: { type: 'statThreshold', stat: 'time', value: 1200 },     bonus: { kind: 'res', res: 'credits', amount: 40 } },
  { id: 'time60',      nameKey: 'ach.time60',      descKey: 'ach.time60.d',      condition: { type: 'statThreshold', stat: 'time', value: 3600 },     bonus: { kind: 'res', res: 'credits', amount: 70 } },
  // ── Тир ядра ──
  { id: 'tier1',       nameKey: 'ach.tier1',       descKey: 'ach.tier1.d',       condition: { type: 'coreTier', tier: 1 },                            bonus: { kind: 'boost', target: 'all', mult: 1.1, dur: 120 } },
  { id: 'tier3',       nameKey: 'ach.tier3',       descKey: 'ach.tier3.d',       condition: { type: 'coreTier', tier: 3 },                            bonus: { kind: 'boost', target: 'all', mult: 1.2, dur: 180 } },
  { id: 'tier5',       nameKey: 'ach.tier5',       descKey: 'ach.tier5.d',       condition: { type: 'coreTier', tier: 5 },                            bonus: { kind: 'boost', target: 'all', mult: 1.25, dur: 180 } },
  // ── Престиж ──
  { id: 'prestige1',   nameKey: 'ach.prestige1',   descKey: 'ach.prestige1.d',   condition: { type: 'prestigeCount', count: 1 },                      bonus: { kind: 'boost', target: 'all', mult: 1.15, dur: 120 } },
  { id: 'prestige3',   nameKey: 'ach.prestige3',   descKey: 'ach.prestige3.d',   condition: { type: 'prestigeCount', count: 3 },                      bonus: { kind: 'boost', target: 'all', mult: 1.2, dur: 180 } },
  // ── Кастомизация: модули и blueprint-узлы ──
  { id: 'mod1',        nameKey: 'ach.mod1',        descKey: 'ach.mod1.d',        condition: { type: 'modulesInstalled', count: 1 },                   bonus: { kind: 'res', res: 'credits', amount: 30 } },
  { id: 'mod4',        nameKey: 'ach.mod4',        descKey: 'ach.mod4.d',        condition: { type: 'modulesInstalled', count: 4 },                   bonus: { kind: 'res', res: 'credits', amount: 80 } },
  { id: 'mod10',       nameKey: 'ach.mod10',       descKey: 'ach.mod10.d',       condition: { type: 'modulesInstalled', count: 10 },                  bonus: { kind: 'boost', target: 'all', mult: 1.15, dur: 180 } },
  { id: 'modNode3',    nameKey: 'ach.modNode3',    descKey: 'ach.modNode3.d',    condition: { type: 'modulesOnNode', count: 3 },                      bonus: { kind: 'res', res: 'credits', amount: 60 } },
  { id: 'modVar5',     nameKey: 'ach.modVar5',     descKey: 'ach.modVar5.d',     condition: { type: 'uniqueModules', count: 5 },                      bonus: { kind: 'res', res: 'credits', amount: 100 } },
  { id: 'modVar10',    nameKey: 'ach.modVar10',    descKey: 'ach.modVar10.d',    condition: { type: 'uniqueModules', count: 10 },                     bonus: { kind: 'boost', target: 'all', mult: 1.2, dur: 240 } },
  { id: 'modCats3',    nameKey: 'ach.modCats3',    descKey: 'ach.modCats3.d',    condition: { type: 'moduleCategories', count: 3 },                   bonus: { kind: 'res', res: 'credits', amount: 120 } },
  { id: 'bp1',         nameKey: 'ach.bp1',         descKey: 'ach.bp1.d',         condition: { type: 'blueprints', count: 1 },                         bonus: { kind: 'res', res: 'credits', amount: 50 } },
  { id: 'bp3',         nameKey: 'ach.bp3',         descKey: 'ach.bp3.d',         condition: { type: 'blueprints', count: 3 },                         bonus: { kind: 'res', res: 'credits', amount: 120 } },
  { id: 'bp5',         nameKey: 'ach.bp5',         descKey: 'ach.bp5.d',         condition: { type: 'blueprints', count: 5 },                         bonus: { kind: 'boost', target: 'all', mult: 1.2, dur: 240 } },
];

// ── Tutorial ─────────────────────────────────────────────────────────────────

export const TUTORIAL_STEPS: { textKey: string }[] = [
  { textKey: 'tut.1' },
  { textKey: 'tut.2' },
  { textKey: 'tut.3' },
  { textKey: 'tut.4' },
  { textKey: 'tut.5' },
];

// ── Localization ─────────────────────────────────────────────────────────────

const RU: Record<string, string> = {
  'hud.net': 'СЕТЬ', 'hud.online': 'В СЕТИ', 'hud.nodes': 'УЗЛЫ', 'hud.links': 'СВЯЗИ',
  'hud.flow': 'ПОТОК', 'hud.pcs': '/с', 'hud.tier': 'ТИР', 'hud.legacy': 'LEGACY',
  'goal.title': 'ЯДРО СЕТИ', 'goal.done': 'ЯДРО ОНЛАЙН',
  'shop.tabNodes': 'УЗЛЫ', 'shop.tabTech': 'ТЕХНОЛОГИИ', 'shop.tabUpg': 'УЛУЧШЕНИЯ', 'shop.tabAch': 'ВЕХИ',
  'shop.locked': 'НУЖНА ТЕХНОЛОГИЯ', 'shop.lockedCore': 'НУЖНО ЯДРО СЕТИ',
  'shop.title': 'СЕТЕВЫЕ УЗЛЫ',
  'shop.pathA': 'ПУТЬ ОБРАБОТКИ', 'shop.pathB': 'ПУТЬ БЕЗОПАСНОСТИ',
  'shop.pathA.d': 'Фрагменты и кредиты: процессор, архив, дата-центр',
  'shop.pathB.d': 'Фильтрация и шифрование: файрвол, ядро шифрования',
  'shop.late': 'АЛЬТ. ПУТЬ · ЦЕНА ×3', 'shop.requires': 'ТРЕБУЕТ',
  'research.name': 'ИССЛЕДОВАНИЕ СЕТИ', 'research.d': '+8% к скорости производства за тир. Бесконечно.',
  'info.upgrade': 'УЛУЧШИТЬ', 'info.delete': 'УДАЛИТЬ', 'info.lvl': 'УР.', 'info.max': 'МАКС',
  'info.recipe': 'Цикл', 'info.rate': 'Скорость',
  'st.online': 'АКТИВЕН', 'st.idle': 'ПРОСТОЙ', 'st.waiting': 'НЕТ ВХОДА', 'st.full': 'ПОЛНЫЙ',
  'tut.skip': 'Пропустить', 'tut.step': 'ШАГ',
  'tut.1': 'Это стартовая сеть: реле передаёт ДАННЫЕ в хранилище. Пакеты уже в пути.',
  'tut.2': 'Откройте магазин и купите ещё один РЕЛЕЙНЫЙ СЕРВЕР.',
  'tut.3': 'Перетащите связь с выхода DATA нового реле на вход хранилища.',
  'tut.4': 'Купите МАРШРУТИЗАТОР — он ветвит поток данных.',
  'tut.5': 'Сервер вычислений + Процессор данных = ФРАГМЕНТЫ. Соберите 100 для Ядра.',
  'off.title': 'СВЯЗЬ ВОССТАНОВЛЕНА',
  'off.body': 'Пока вас не было, сеть продолжала работать:',
  'off.time': 'Оффлайн', 'off.h': 'ч',
  'off.collect': 'ЗАБРАТЬ',
  'core.title': 'ЯДРО СЕТИ ОНЛАЙН',
  'core.body': 'Порог fragments пройден — ядро запущено и вышло на новый тир. Открыт узел «Ядро сети», производство ускорено.',
  'core.go': 'ПРОДОЛЖИТЬ',
  'toast.mile': 'Ядро сети заряжено на {p}%',
  'toast.tier': 'ЯДРО СЕТИ · ТИР {t}! Скорость производства +10%',
  'toast.surge': 'Пойман всплеск данных: производство ×3 на 15 секунд!',
  'toast.ach': 'ВЕХА: {name}',
  'toast.prestige': 'Сеть пересобрана. Legacy +{n}',
  'toast.research': 'Исследование завершено: тир {t}',
  'surge.tag': 'ВСПЛЕСК!', 'surge.x': '×3',
  'node.reserve': 'РЕЗЕРВ',
  'tip.storage': 'Хранилище копит DATA и переводит их в общий резерв — резерв тратится на покупки. Чем полнее, тем быстрее.',
  'prestige.title': 'NETWORK RESET',
  'prestige.body': 'Сбросить узлы, связи, ресурсы и технологии. Взамен вы получите постоянные LEGACY POINTS (по накопленным кредитам забега) и +2% к скорости производства за каждое очко. Каждый следующий забег дороже, но и мощнее.',
  'prestige.gain': 'ВЫ ПОЛУЧИТЕ', 'prestige.mult': 'Множитель скорости',
  'prestige.confirm': 'ПЕРЕСОБРАТЬ СЕТЬ', 'prestige.cancel': 'ОТМЕНА',
  'prestige.need': 'Доступно после запуска Ядра сети (тир 1)',
  'lb.title': 'СЕТЕВАЯ МОЩЬ · ТОП ОПЕРАТОРОВ', 'lb.power': 'МОЩЬ', 'lb.tier': 'ТИР',
  'lb.empty': 'Пока нет результатов — ваша сеть станет первой.', 'lb.you': 'ВЫ',
  'ach.done': 'ВЫПОЛНЕНО', 'ach.reward': 'НАГРАДА', 'ach.progress': 'Вехи',
  'ach.bonusRes': '+{n} {res}',
  'ach.bonusBoost': '+{p}% {tgt} · {d}с',
  'ach.tgt.gen': 'генерация', 'ach.tgt.proc': 'обработка', 'ach.tgt.all': 'всё производство',
  'ach.relay3': 'Три реле', 'ach.relay3.d': 'Постройте 3 релейных сервера',
  'ach.conn5': 'Первые связи', 'ach.conn5.d': 'Создайте 5 связей',
  'ach.storage3': 'Складской район', 'ach.storage3.d': 'Постройте 3 хранилища',
  'ach.credits50': 'Первая прибыль', 'ach.credits50.d': 'Заработайте 50 кредитов за забег',
  'ach.frag10': 'Осколки', 'ach.frag10.d': 'Соберите 10 фрагментов данных',
  'ach.chain4': 'Магистраль', 'ach.chain4.d': 'Цепочка из 4 узлов подряд',
  'ach.relay8': 'Релейная ферма', 'ach.relay8.d': 'Постройте 8 релейных серверов',
  'ach.nodes10': 'Десяток', 'ach.nodes10.d': '10 узлов в сети одновременно',
  'ach.conn15': 'Коммутация', 'ach.conn15.d': 'Создайте 15 связей',
  'ach.tech2': 'Исследователь', 'ach.tech2.d': 'Откройте 2 технологии',
  'ach.upg3': 'Тюнинг', 'ach.upg3.d': 'Улучшите узлы 3 раза',
  'ach.time5': 'Дежурная смена', 'ach.time5.d': '5 минут непрерывной работы сети',
  'ach.credits500': 'Крупный контракт', 'ach.credits500.d': 'Заработайте 500 кредитов за забег',
  'ach.frag50': 'Полпути', 'ach.frag50.d': 'Соберите 50 фрагментов данных',
  'ach.chain6': 'Хребет сети', 'ach.chain6.d': 'Цепочка из 6 узлов подряд',
  'ach.nodes25': 'Мегаполис', 'ach.nodes25.d': '25 узлов в сети одновременно',
  'ach.time20': 'Ночная смена', 'ach.time20.d': '20 минут непрерывной работы',
  'ach.tier1': 'Ядро живо', 'ach.tier1.d': 'Достигните тира 1 Ядра сети',
  'ach.prestige1': 'Второе дыхание', 'ach.prestige1.d': 'Выполните Network Reset',
  'ach.router3': 'Развязка', 'ach.router3.d': 'Постройте 3 маршрутизатора',
  'ach.compute3': 'Вычислительный кластер', 'ach.compute3.d': 'Постройте 3 сервера вычислений',
  'ach.processor3': 'Цех обработки', 'ach.processor3.d': 'Постройте 3 процессора данных',
  'ach.processor8': 'Конвейер', 'ach.processor8.d': 'Постройте 8 процессоров данных',
  'ach.firewall3': 'Периметр', 'ach.firewall3.d': 'Постройте 3 файрвола',
  'ach.variety5': 'Разнообразие', 'ach.variety5.d': '5 разных типов узлов в сети',
  'ach.variety8': 'Экосистема', 'ach.variety8.d': '8 разных типов узлов в сети',
  'ach.variety12': 'Полный стек', 'ach.variety12.d': '12 разных типов узлов в сети',
  'ach.conn30': 'Паутина', 'ach.conn30.d': 'Создайте 30 связей',
  'ach.chain10': 'Сквозной канал', 'ach.chain10.d': 'Цепочка из 10 узлов подряд',
  'ach.credits2000': 'Магнат', 'ach.credits2000.d': 'Заработайте 2000 кредитов за забег',
  'ach.frag200': 'Архивариус', 'ach.frag200.d': 'Соберите 200 фрагментов данных',
  'ach.tech5': 'Технократ', 'ach.tech5.d': 'Откройте 5 технологий',
  'ach.upg10': 'Инженер', 'ach.upg10.d': 'Улучшите узлы 10 раз',
  'ach.time60': 'Марафон', 'ach.time60.d': '60 минут непрерывной работы',
  'ach.tier3': 'Ядро крепнет', 'ach.tier3.d': 'Достигните тира 3 Ядра сети',
  'ach.tier5': 'Ядро-гигант', 'ach.tier5.d': 'Достигните тира 5 Ядра сети',
  'ach.prestige3': 'Циклы', 'ach.prestige3.d': 'Выполните Network Reset 3 раза',
  'ach.mod1': 'Модернизация', 'ach.mod1.d': 'Установите первый модуль на узел',
  'ach.mod4': 'Инженер сетей', 'ach.mod4.d': 'Установите 4 модуля',
  'ach.mod10': 'Архитектор', 'ach.mod10.d': '10 модулей установлено суммарно',
  'ach.modNode3': 'Полная комплектация', 'ach.modNode3.d': '3 модуля на одном узле',
  'ach.modVar5': 'Коллекционер', 'ach.modVar5.d': '5 разных типов модулей в сети',
  'ach.modVar10': 'Мастер кастомизации', 'ach.modVar10.d': '10 разных типов модулей в сети',
  'ach.modCats3': 'Универсальная сборка', 'ach.modCats3.d': 'Модули на узлах трёх категорий одновременно',
  'ach.bp1': 'Первый чертёж', 'ach.bp1.d': 'Получите blueprint-узел из исследования',
  'ach.bp3': 'Конструктор', 'ach.bp3.d': 'Получите 3 blueprint-узла',
  'ach.bp5': 'Серийное производство', 'ach.bp5.d': 'Получите 5 blueprint-узлов',
  'mod.overclock': 'РАЗГОН', 'mod.overclock.d': 'Циклы на 50% быстрее, но буферы −30%.',
  'mod.bulkBuffer': 'ОБЪЁМНЫЙ БУФЕР', 'mod.bulkBuffer.d': '+80% к вместимости, −20% к скорости.',
  'mod.deepStore': 'ГЛУБОКОЕ ХРАНИЛИЩЕ', 'mod.deepStore.d': 'Вместимость ×2.5, конвертация в резерв −40%.',
  'mod.coldStorage': 'ХОЛОДНОЕ ХРАНИЛИЩЕ', 'mod.coldStorage.d': '+60% вместимости, дренаж в резерв −25%.',
  'mod.byproduct': 'ЭКСТРАКТОР ПОБОЧКИ', 'mod.byproduct.d': '+1 кредит за цикл, но первый вход +1.',
  'mod.scrapHarvester': 'СБОРЩИК ОБРЕЗКОВ', 'mod.scrapHarvester.d': '+1 DATA в резерв за цикл, первый вход +1.',
  'mod.efficiencyCore': 'ЯДРО ЭФФЕКТИВНОСТИ', 'mod.efficiencyCore.d': 'Первый вход рецепта −1 (минимум 1). Занимает 2 слота.',
  'mod.redundancy': 'РЕЗЕРВНЫЙ КОНТУР', 'mod.redundancy.d': '8 секунд работает без входа, но всегда −15% скорости.',
  'mod.neuralCache': 'НЕЙРОКЭШ', 'mod.neuralCache.d': '+60% скорости, −40% вместимости. 2 слота.',
  'mod.heatSink': 'РАДИАТОР', 'mod.heatSink.d': '+50% вместимости, −10% скорости.',
  'mod.fluxCapacitor': 'ФЛЮКС-КОНДЕНСАТОР', 'mod.fluxCapacitor.d': '+30% скорости генерации, −15% буфера.',
  'mod.twinCoil': 'ДВОЙНАЯ КАТУШКА', 'mod.twinCoil.d': '+1 DATA за цикл генератора. 2 слота.',
  'mod.surgeTap': 'ЛОВЕШКА ВСПЛЕСКОВ', 'mod.surgeTap.d': 'Окно поимки всплеска данных +4 секунды.',
  'mod.packetRouter': 'ПАКЕТНЫЙ КОММУТАТОР', 'mod.packetRouter.d': 'Буфер передачи ×2.',
  'mod.qosBalancer': 'QoS-БАЛАНСИР', 'mod.qosBalancer.d': '+40% к буферу передачи.',
  'mod.harmonicFilter': 'ГАРМОНИЧЕСКИЙ ФИЛЬТР', 'mod.harmonicFilter.d': '+1 отфильтрованные данные за цикл, первый вход +1.',
  'mod.slots': 'СЛОТЫ', 'mod.install': 'УСТАНОВИТЬ', 'mod.remove': 'СНЯТЬ',
  'mod.refund': 'возврат 50%', 'mod.empty': 'пусто',
  'mod.choice.title': 'ПРОРЫВ ИССЛЕДОВАНИЯ',
  'mod.choice.body': 'Лаборатория собрала два прототипа. Разблокируйте один модуль:',
  'mod.unlocked': 'Модуль разблокирован: {name}',
  'bp.title': 'ЧЕРТЁЖ', 'bp.shop': 'ЧЕРТЕЖИ',
  'bp.toast': 'Получен чертёж: {name}',
  'bp.built': 'Особый вариант узла со случайными характеристиками рецепта.',
  'toast.modInstall': 'Модуль установлен', 'toast.modRemove': 'Модуль снят: возврат 50%',
  'toast.noSlots': 'Нет свободных слотов',
  'dev.fast': 'DEV: время ×8', 'dev.normal': 'DEV: время ×1',
  'help.title': 'РУКОВОДСТВО ОПЕРАТОРА',
  'help.d1': 'ЛКМ — выбрать узел, тянуть — переместить',
  'help.d2': 'Тянуть с порта OUT на порт IN — создать связь',
  'help.d3': 'ПКМ — удалить узел или связь, отменить размещение',
  'help.d4': 'Колесо — масштаб · WASD / средняя кнопка — камера',
  'help.m1': 'Палец по узлу — перенос · с порта — связь',
  'help.m2': 'Палец по фону — камера · щипок — масштаб',
  'help.rule': 'ОДИН ПОРТ = ОДНА СВЯЗЬ · ТОЛЬКО ВЫХОД → ВХОД',
  'help.close': 'ЗАКРЫТЬ',
  'menu.help': 'УПРАВЛЕНИЕ', 'menu.codex': 'СПРАВОЧНИК', 'menu.reset': 'СБРОС СЕТИ',
  'menu.confirm': 'ТОЧНО СБРОСИТЬ?', 'menu.grid': 'Сетка', 'menu.zoomIn': 'Приблизить',
  'menu.zoomOut': 'Отдалить', 'menu.fit': 'Камера к стартовой зоне',
  'msg.place': 'Кликните по карте — разместить · ПКМ / Esc — отмена',
  'toast.notEnough': 'Недостаточно ресурсов',
  'toast.conn': 'Связь установлена',
  'toast.errPort': 'Порт занят',
  'toast.errCompat': 'Несовместимые ресурсы',
  'toast.errSelf': 'Нельзя соединить узел с собой',
  'toast.errDir': 'Связь: только ВЫХОД → ВХОД',
  'toast.tech': 'Технология открыта',
  'toast.saved': 'Сохранено',
  'toast.tutDone': 'Обучение завершено',
  'toast.nodeUpg': 'Узел улучшен',
  'toast.upg': 'Улучшение куплено',
  'toast.reset': 'Сеть сброшена',
  'toast.core': 'ЯДРО СЕТИ ОНЛАЙН',
  'res.data': 'ДАННЫЕ', 'res.compute': 'ВЫЧИСЛЕНИЯ', 'res.processed': 'ОБРАБОТАННЫЕ',
  'res.filtered': 'ОТФИЛЬТРОВАННЫЕ', 'res.encrypted': 'ЗАШИФРОВАННЫЕ',
  'res.fragment': 'ФРАГМЕНТЫ', 'res.credits': 'КРЕДИТЫ', 'res.signal': 'СИГНАЛ',
  'resd.data': 'Сырьё сети. Производится реле, потребляется почти всеми узлами. Также валюта покупок (верхняя панель).',
  'resd.signal': 'Сырой сигнал сенсорных решёток. Потребляется только анализаторами.',
  'resd.compute': 'Вычислительный ресурс серверов фермы. Нужен процессорам, шифрованию и дата-центру.',
  'resd.processed': 'Продукт прокси-серверов. Компонент для дата-центра и синтезатора.',
  'resd.filtered': 'Продукт файрволов. Нужен для шифрования и синтезатора.',
  'resd.encrypted': 'Продукт ядер шифрования. Компонент дата-центра.',
  'resd.fragment': 'Ресурс прогресса. Заполняет тиры Ядра сети — каждый тир ускоряет производство.',
  'resd.credits': 'Сетевая валюта. Покупка продвинутых узлов, технологий и улучшений.',
  'nd.relay': 'РЕЛЕЙНЫЙ СЕРВЕР', 'nd.relay.d': 'Генерирует ДАННЫЕ. Основа любой сети.',
  'nd.storage': 'ХРАНИЛИЩЕ ДАННЫХ', 'nd.storage.d': 'Копит ДАННЫЕ и переводит их в резерв (чем полнее — тем быстрее). DATA OUT раздаёт накопленное дальше.',
  'nd.cache': 'КЭШ ДАННЫХ', 'nd.cache.d': 'Компактный буфер между узлами: сглаживает поток ДАННЫХ.',
  'nd.compute': 'СЕРВЕР ВЫЧИСЛЕНИЙ', 'nd.compute.d': 'Генерирует ВЫЧИСЛЕНИЯ для процессоров.',
  'nd.router': 'МАРШРУТИЗАТОР', 'nd.router.d': 'Раздаёт ДАННЫЕ по двум направлениям.',
  'nd.balancer': 'БАЛАНСИРОВЩИК', 'nd.balancer.d': 'Мощная развязка: до 4 направлений из 2 входов.',
  'nd.proxy': 'ПРОКСИ-СЕРВЕР', 'nd.proxy.d': 'Преобразует ДАННЫЕ в ОБРАБОТАННЫЕ ДАННЫЕ.',
  'nd.processor': 'ПРОЦЕССОР ДАННЫХ', 'nd.processor.d': 'Собирает ФРАГМЕНТЫ из ДАННЫХ и ВЫЧИСЛЕНИЙ.',
  'nd.archive': 'АРХИВ', 'nd.archive.d': 'Архивирует ДАННЫЕ напрямую в СЕТЕВЫЕ КРЕДИТЫ.',
  'nd.firewall': 'ФАЙРВОЛ', 'nd.firewall.d': 'Фильтрует ДАННЫЕ в ОТФИЛЬТРОВАННЫЕ ДАННЫЕ.',
  'nd.encryption': 'ЯДРО ШИФРОВАНИЯ', 'nd.encryption.d': 'Создаёт ЗАШИФРОВАННЫЕ ДАННЫЕ.',
  'nd.refinery': 'СИНТЕЗАТОР', 'nd.refinery.d': 'Синтезирует ФРАГМЕНТЫ из обработанных и отфильтрованных данных.',
  'nd.datacenter': 'ДАТА-ЦЕНТР', 'nd.datacenter.d': 'Монетизирует поток: производит СЕТЕВЫЕ КРЕДИТЫ.',
  'nd.hub': 'СЕТЕВОЙ ХАБ', 'nd.hub.d': 'Многопортовый узел для крупных магистралей.',
  'nd.core': 'ЯДРО СЕТИ', 'nd.core.d': 'Сердце инфраструктуры: ДАННЫЕ + ВЫЧИСЛЕНИЯ в большой поток кредитов.',
  'nd.sensor': 'СЕНСОРНАЯ РЕШЁТКА', 'nd.sensor.d': 'Улавливает сырой СИГНАЛ извне. Кормит анализаторы.',
  'nd.signalbuffer': 'БУФЕР СИГНАЛА', 'nd.signalbuffer.d': 'Накапливает СИГНАЛ и раздаёт его анализаторам.',
  'nd.analyzer': 'АНАЛИЗАТОР', 'nd.analyzer.d': 'Разбирает СИГНАЛ и ВЫЧИСЛЕНИЯ на ФРАГМЕНТЫ.',
  'nd.computebank': 'БАНК ВЫЧИСЛЕНИЙ', 'nd.computebank.d': 'Хранилище ВЫЧИСЛЕНИЙ: копит и раздаёт мощность процессорам.',
  'nd.smartrouter': 'СМАРТ-МАРШРУТИЗАТОР', 'nd.smartrouter.d': 'Гибкая развязка: 3 входа и 3 выхода для ДАННЫХ.',
  'nd.compressor': 'КОМПРЕССОР', 'nd.compressor.d': 'Сжимает ОБРАБОТАННЫЕ и ДАННЫЕ в СЕТЕВЫЕ КРЕДИТЫ.',
  'nd.assembler': 'СБОРЩИК', 'nd.assembler.d': 'Собирает ФРАГМЕНТЫ из ЗАШИФРОВАННЫХ и ОБРАБОТАННЫХ данных.',
  'nd.forge': 'КУЗНЯ', 'nd.forge.d': 'Переплавляет ЗАШИФРОВАННЫЕ данные и ВЫЧИСЛЕНИЯ в КРЕДИТЫ.',
  'tc.routing': 'РАСШИР. МАРШРУТИЗАЦИЯ', 'tc.routing.d': 'Открывает Прокси-сервер, Балансировщик и Смарт-маршрутизатор. База для выбора пути.',
  'tc.processing': 'ОБРАБОТКА ДАННЫХ', 'tc.processing.d': 'Путь обработки: Процессор данных, Архив и Банк вычислений.',
  'tc.telemetry': 'ТЕЛЕМЕТРИЯ', 'tc.telemetry.d': 'Сырьевая волна: Сенсорная решётка, Буфер сигнала и Анализатор.',
  'tc.security': 'УРОВЕНЬ БЕЗОПАСНОСТИ', 'tc.security.d': 'Путь безопасности: Файрвол и Компрессор.',
  'tc.encryptionTech': 'ШИФРОВАНИЕ', 'tc.encryptionTech.d': 'Продолжение пути безопасности: Ядро шифрования и Сборщик.',
  'tc.distributed': 'РАСПРЕД. ВЫЧИСЛЕНИЯ', 'tc.distributed.d': 'Вершина пути обработки: Дата-центр, Хаб, Синтезатор и Кузня.',
  'up.bandwidth': 'ПРОПУСКНАЯ СПОСОБНОСТЬ', 'up.bandwidth.d': '+50% к пропускной способности всех связей. Без предела.',
  'up.storageCap': 'ОБЪЁМ ХРАНИЛИЩ', 'up.storageCap.d': '+50% к вместимости хранилищ данных. Без предела.',
  'up.prodSpeed': 'СКОРОСТЬ ГЕНЕРАЦИИ', 'up.prodSpeed.d': 'Генераторы работают на 12% быстрее. Без предела.',
  'up.procSpeed': 'СКОРОСТЬ ОБРАБОТКИ', 'up.procSpeed.d': 'Процессоры работают на 12% быстрее. Без предела.',
  'up.packetSize': 'РАЗМЕР ПАКЕТА', 'up.packetSize.d': 'Каждый пакет несёт +1 единицу ресурса. Без предела.',
  'start.tag': 'ОПЕРАТОР ЭКСПЕРИМЕНТАЛЬНОЙ ЦИФРОВОЙ СЕТИ',
  'start.desc': 'Размещайте узлы, соединяйте порты — потоки данных сами разгонят сеть до полноценной цифровой инфраструктуры.',
  'start.play': 'ЗАПУСТИТЬ СЕТЬ',
  'start.continue': 'ПРОДОЛЖИТЬ',
  'start.codex': 'ОТКРЫТЬ СПРАВОЧНИК',
  'start.tip': 'Автосейв каждые 5 секунд · оффлайн-прогресс до 8 часов',
  'start.chain': 'БАЗОВАЯ ЦЕПОЧКА',
  'start.controls': 'УПРАВЛЕНИЕ',
  'codex.title': 'СПРАВОЧНИК ОПЕРАТОРА',
  'codex.tabNodes': 'УЗЛЫ', 'codex.tabRes': 'РЕСУРСЫ', 'codex.tabLinks': 'СВЯЗИ', 'codex.tabFaq': 'FAQ',
  'codex.cat.generator': 'ГЕНЕРАТОРЫ', 'codex.cat.storage': 'ХРАНИЛИЩЕ',
  'codex.cat.transfer': 'МАРШРУТИЗАЦИЯ', 'codex.cat.processor': 'ОБРАБОТКА',
  'codex.in': 'ВХОД', 'codex.out': 'ВЫХОД', 'codex.none': '—', 'codex.src': 'источник',
  'codex.cycle': 'ЦИКЛ', 'codex.buf': 'БУФЕР', 'codex.sec': 'с',
  'codex.basic': 'БАЗОВЫЙ', 'codex.wallet': 'в резерв', 'codex.goal': 'в прогресс',
  'codex.linksTitle': 'КАК СОЕДИНЯТЬ УЗЛЫ',
  'cx.r1': 'Связь создаётся только из порта OUT в порт IN: зажмите OUT и дотяните до IN.',
  'cx.r2': 'Цвет порта — это ресурс. Соединяются только порты одного цвета.',
  'cx.r3': 'Один порт = одна связь. Занятый порт подсвечен заполненным квадратом.',
  'cx.r4': 'Генераторы (реле, сервер вычислений) не имеют входов — они источники. Хранилище имеет и вход, и выход.',
  'cx.r5': 'ПКМ по линии или узлу — удаление. На мобильном — выделить узел и нажать «УДАЛИТЬ».',
  'cx.bw': 'У каждой связи есть пропускная способность (по умолчанию 2 ед/с). Янтарная линия — связь перегружена. Улучшайте «ПРОПУСКНУЮ СПОСОБНОСТЬ».',
  'codex.resTitle': 'ДВА СЛОЯ РЕСУРСОВ',
  'codex.resBody': 'Цветные ресурсы текут по связям между узлами. DATA и CREDITS дополнительно живут в глобальном резерве (верхняя панель) — именно из резерва оплачиваются покупки. ФРАГМЕНТЫ заряжают тиры Ядра сети.',
  'faq.q1': 'С чего начать?',
  'faq.a1': 'Реле производит ДАННЫЕ → хранилище копит их и переводит в резерв (это деньги на покупки). Накопив ДАННЫЕ, купите маршрутизатор и сервер вычислений, затем процессор — он собирает ФРАГМЕНТЫ.',
  'faq.q2': 'Откуда берутся деньги на покупки?',
  'faq.a2': 'Хранилище конвертирует накопленные ДАННЫЕ в общий резерв — тем быстрее, чем полнее буфер. Следите за индикатором «→ РЕЗЕРВ» на карточке хранилища и за стрелкой роста под счётчиком DATA.',
  'faq.q3': 'Как раздать данные нескольким узлам?',
  'faq.a3': 'Маршрутизатор: 1 вход → 2 выхода. Балансировщик: 2 входа → 4 выхода. Хранилище и кэш работают как промежуточные буферы с собственным выходом.',
  'faq.q4': 'Почему не создаётся связь?',
  'faq.a4': 'Только OUT → IN; цвета портов совпадают; оба порта свободны; нельзя соединить узел с собой. Причина пишется прямо у курсора.',
  'faq.q5': 'Где брать ФРАГМЕНТЫ?',
  'faq.a5': 'Процессор данных: 2 ДАННЫХ + 1 ВЫЧИСЛЕНИЕ → 1 ФРАГМЕНТ. Позже — синтезатор: обработанные + отфильтрованные данные → фрагмент.',
  'faq.q6': 'Как зарабатывать СЕТЕВЫЕ КРЕДИТЫ?',
  'faq.a6': 'Архив (данные → кредиты), дата-центр (обработанные + зашифрованные + вычисления → кредиты) и узел «Ядро сети».',
  'faq.q7': 'Что значат статусы узлов?',
  'faq.a7': 'АКТИВЕН — работает. НЕТ ВХОДА — ждёт ресурс (значок разорванной цепи). ПОЛНЫЙ — некому забирать, подключите OUT-порт (значок переполнения). ПРОСТОЙ — нет данных.',
  'faq.q8': 'Что такое ВСПЛЕСК ДАННЫХ?',
  'faq.a8': 'Случайный генератор иногда подсвечивается янтарным на 8 секунд. Кликните по нему — 15 секунд он производит в 3 раза больше. Не успели — всплеск исчезает без штрафа.',
  'faq.q9': 'Как работает Ядро сети и его тиры?',
  'faq.a9': 'Фрагменты заполняют текущий тир ядра (100 → 500 → 2500 …). Каждый пройденный тир даёт +10% к скорости производства навсегда и усиливает визуал ядра. Предела тиров нет.',
  'faq.q10': 'Что такое Network Reset и Legacy Points?',
  'faq.a10': 'После тира 1 ядра доступен Network Reset: сеть обнуляется, но вы получаете постоянные Legacy Points (√кредитов забега ÷ 10) и +2% скорости за очко. Новые забеги дороже, но масштабнее.',
  'faq.q11': 'Работает ли сеть без меня?',
  'faq.a11': 'Да. При возвращении игра посчитает оффлайн-производство (до 8 часов, 50% эффективности) и предложит его забрать.',
  'faq.q12': 'Как удалить узел или связь?',
  'faq.a12': 'ПКМ по узлу или линии (на мобильном — выделить узел → «УДАЛИТЬ»). Связи узла удаляются вместе с ним. Стоимость не возвращается.',
};

const EN: Record<string, string> = {
  'hud.net': 'NETWORK', 'hud.online': 'ONLINE', 'hud.nodes': 'NODES', 'hud.links': 'LINKS',
  'hud.flow': 'FLOW', 'hud.pcs': '/s', 'hud.tier': 'TIER', 'hud.legacy': 'LEGACY',
  'goal.title': 'NETWORK CORE', 'goal.done': 'CORE ONLINE',
  'shop.tabNodes': 'NODES', 'shop.tabTech': 'TECH', 'shop.tabUpg': 'UPGRADES', 'shop.tabAch': 'MILESTONES',
  'shop.locked': 'REQUIRES TECH', 'shop.lockedCore': 'REQUIRES NETWORK CORE',
  'shop.title': 'NETWORK NODES',
  'shop.pathA': 'PROCESSING PATH', 'shop.pathB': 'SECURITY PATH',
  'shop.pathA.d': 'Fragments & credits: processor, archive, data center',
  'shop.pathB.d': 'Filtering & encryption: firewall, encryption core',
  'shop.late': 'ALT PATH · COST ×3', 'shop.requires': 'REQUIRES',
  'research.name': 'NETWORK RESEARCH', 'research.d': '+8% production speed per tier. Endless.',
  'info.upgrade': 'UPGRADE', 'info.delete': 'DELETE', 'info.lvl': 'LV.', 'info.max': 'MAX',
  'info.recipe': 'Cycle', 'info.rate': 'Rate',
  'st.online': 'ONLINE', 'st.idle': 'IDLE', 'st.waiting': 'NO INPUT', 'st.full': 'FULL',
  'tut.skip': 'Skip', 'tut.step': 'STEP',
  'tut.1': 'This is your starter network: the relay feeds DATA into storage. Packets are already flowing.',
  'tut.2': 'Open the shop and buy another RELAY SERVER.',
  'tut.3': 'Drag a link from the new relay DATA OUT port to the storage input.',
  'tut.4': 'Buy a ROUTER — it branches your data flow.',
  'tut.5': 'Compute Server + Data Processor = FRAGMENTS. Collect 100 to build the Core.',
  'off.title': 'CONNECTION RESTORED',
  'off.body': 'While you were away, the network kept running:',
  'off.time': 'Offline', 'off.h': 'h',
  'off.collect': 'COLLECT',
  'core.title': 'NETWORK CORE ONLINE',
  'core.body': 'Fragment threshold cleared — the core reached a new tier. The Network Core node is available and production is faster.',
  'core.go': 'CONTINUE',
  'toast.mile': 'Network core charged to {p}%',
  'toast.tier': 'NETWORK CORE · TIER {t}! Production speed +10%',
  'toast.surge': 'Data surge caught: ×3 production for 15 seconds!',
  'toast.ach': 'MILESTONE: {name}',
  'toast.prestige': 'Network rebuilt. Legacy +{n}',
  'toast.research': 'Research complete: tier {t}',
  'surge.tag': 'SURGE!', 'surge.x': '×3',
  'node.reserve': 'RESERVE',
  'tip.storage': 'Storage banks DATA and converts it to your reserve — the reserve pays for purchases. Fuller = faster.',
  'prestige.title': 'NETWORK RESET',
  'prestige.body': 'Wipe nodes, links, resources and techs. In return you gain permanent LEGACY POINTS (from run credits) and +2% production speed per point. Next runs cost more but scale bigger.',
  'prestige.gain': 'YOU GAIN', 'prestige.mult': 'Speed multiplier',
  'prestige.confirm': 'REBUILD NETWORK', 'prestige.cancel': 'CANCEL',
  'prestige.need': 'Unlocks after Network Core tier 1',
  'lb.title': 'NETWORK POWER · TOP OPERATORS', 'lb.power': 'POWER', 'lb.tier': 'TIER',
  'lb.empty': 'No entries yet — your network will be the first.', 'lb.you': 'YOU',
  'ach.done': 'DONE', 'ach.reward': 'REWARD', 'ach.progress': 'Milestones',
  'ach.bonusRes': '+{n} {res}',
  'ach.bonusBoost': '+{p}% {tgt} · {d}s',
  'ach.tgt.gen': 'generation', 'ach.tgt.proc': 'processing', 'ach.tgt.all': 'all production',
  'ach.relay3': 'Three relays', 'ach.relay3.d': 'Build 3 relay servers',
  'ach.conn5': 'First links', 'ach.conn5.d': 'Create 5 connections',
  'ach.storage3': 'Warehouse district', 'ach.storage3.d': 'Build 3 storages',
  'ach.credits50': 'First profit', 'ach.credits50.d': 'Earn 50 credits in one run',
  'ach.frag10': 'Shards', 'ach.frag10.d': 'Collect 10 data fragments',
  'ach.chain4': 'Backbone', 'ach.chain4.d': 'A chain of 4 connected nodes',
  'ach.relay8': 'Relay farm', 'ach.relay8.d': 'Build 8 relay servers',
  'ach.nodes10': 'A dozen', 'ach.nodes10.d': '10 nodes online at once',
  'ach.conn15': 'Switchboard', 'ach.conn15.d': 'Create 15 connections',
  'ach.tech2': 'Researcher', 'ach.tech2.d': 'Unlock 2 technologies',
  'ach.upg3': 'Tuning', 'ach.upg3.d': 'Upgrade nodes 3 times',
  'ach.time5': 'Day shift', 'ach.time5.d': '5 minutes of continuous uptime',
  'ach.credits500': 'Big contract', 'ach.credits500.d': 'Earn 500 credits in one run',
  'ach.frag50': 'Halfway', 'ach.frag50.d': 'Collect 50 data fragments',
  'ach.chain6': 'Network spine', 'ach.chain6.d': 'A chain of 6 connected nodes',
  'ach.nodes25': 'Megalopolis', 'ach.nodes25.d': '25 nodes online at once',
  'ach.time20': 'Night shift', 'ach.time20.d': '20 minutes of continuous uptime',
  'ach.tier1': 'The core lives', 'ach.tier1.d': 'Reach Network Core tier 1',
  'ach.prestige1': 'Second wind', 'ach.prestige1.d': 'Perform a Network Reset',
  'ach.router3': 'Junction', 'ach.router3.d': 'Build 3 routers',
  'ach.compute3': 'Compute cluster', 'ach.compute3.d': 'Build 3 compute servers',
  'ach.processor3': 'Processing floor', 'ach.processor3.d': 'Build 3 data processors',
  'ach.processor8': 'Assembly line', 'ach.processor8.d': 'Build 8 data processors',
  'ach.firewall3': 'Perimeter', 'ach.firewall3.d': 'Build 3 firewalls',
  'ach.variety5': 'Variety', 'ach.variety5.d': '5 different node types in your network',
  'ach.variety8': 'Ecosystem', 'ach.variety8.d': '8 different node types in your network',
  'ach.variety12': 'Full stack', 'ach.variety12.d': '12 different node types in your network',
  'ach.conn30': 'The web', 'ach.conn30.d': 'Create 30 connections',
  'ach.chain10': 'Throughput channel', 'ach.chain10.d': 'A chain of 10 nodes in a row',
  'ach.credits2000': 'Magnate', 'ach.credits2000.d': 'Earn 2000 credits in one run',
  'ach.frag200': 'Archivist', 'ach.frag200.d': 'Collect 200 data fragments',
  'ach.tech5': 'Technocrat', 'ach.tech5.d': 'Unlock 5 technologies',
  'ach.upg10': 'Engineer', 'ach.upg10.d': 'Upgrade nodes 10 times',
  'ach.time60': 'Marathon', 'ach.time60.d': '60 minutes of continuous uptime',
  'ach.tier3': 'Core hardens', 'ach.tier3.d': 'Reach Network Core tier 3',
  'ach.tier5': 'Core colossus', 'ach.tier5.d': 'Reach Network Core tier 5',
  'ach.prestige3': 'Cycles', 'ach.prestige3.d': 'Perform 3 Network Resets',
  'ach.mod1': 'Modded', 'ach.mod1.d': 'Install your first module on a node',
  'ach.mod4': 'Network engineer', 'ach.mod4.d': 'Install 4 modules',
  'ach.mod10': 'Architect', 'ach.mod10.d': '10 modules installed in total',
  'ach.modNode3': 'Fully loaded', 'ach.modNode3.d': '3 modules on a single node',
  'ach.modVar5': 'Collector', 'ach.modVar5.d': '5 different module types in your network',
  'ach.modVar10': 'Customization master', 'ach.modVar10.d': '10 different module types in your network',
  'ach.modCats3': 'Universal build', 'ach.modCats3.d': 'Modules on nodes of three categories at once',
  'ach.bp1': 'First blueprint', 'ach.bp1.d': 'Receive a blueprint node from research',
  'ach.bp3': 'Constructor', 'ach.bp3.d': 'Receive 3 blueprint nodes',
  'ach.bp5': 'Mass production', 'ach.bp5.d': 'Receive 5 blueprint nodes',
  'mod.overclock': 'OVERCLOCK CHIP', 'mod.overclock.d': 'Cycles 50% faster, but buffers −30%.',
  'mod.bulkBuffer': 'BULK BUFFER', 'mod.bulkBuffer.d': '+80% capacity, −20% speed.',
  'mod.deepStore': 'DEEP STORE', 'mod.deepStore.d': 'Capacity ×2.5, reserve conversion −40%.',
  'mod.coldStorage': 'COLD STORAGE', 'mod.coldStorage.d': '+60% capacity, reserve drain −25%.',
  'mod.byproduct': 'BYPRODUCT EXTRACTOR', 'mod.byproduct.d': '+1 credit per cycle, but first input +1.',
  'mod.scrapHarvester': 'SCRAP HARVESTER', 'mod.scrapHarvester.d': '+1 DATA to reserve per cycle, first input +1.',
  'mod.efficiencyCore': 'EFFICIENCY CORE', 'mod.efficiencyCore.d': 'First recipe input −1 (min 1). Takes 2 slots.',
  'mod.redundancy': 'REDUNDANCY MODULE', 'mod.redundancy.d': 'Runs 8s without input, but always −15% speed.',
  'mod.neuralCache': 'NEURAL CACHE', 'mod.neuralCache.d': '+60% speed, −40% capacity. 2 slots.',
  'mod.heatSink': 'HEAT SINK', 'mod.heatSink.d': '+50% capacity, −10% speed.',
  'mod.fluxCapacitor': 'FLUX CAPACITOR', 'mod.fluxCapacitor.d': '+30% generation speed, −15% buffer.',
  'mod.twinCoil': 'TWIN COIL', 'mod.twinCoil.d': '+1 DATA per generator cycle. 2 slots.',
  'mod.surgeTap': 'SURGE TAP', 'mod.surgeTap.d': 'Data surge catch window +4 seconds.',
  'mod.packetRouter': 'PACKET ROUTER', 'mod.packetRouter.d': 'Transfer buffer ×2.',
  'mod.qosBalancer': 'QOS BALANCER', 'mod.qosBalancer.d': '+40% transfer buffer.',
  'mod.harmonicFilter': 'HARMONIC FILTER', 'mod.harmonicFilter.d': '+1 filtered data per cycle, first input +1.',
  'mod.slots': 'SLOTS', 'mod.install': 'INSTALL', 'mod.remove': 'REMOVE',
  'mod.refund': '50% refund', 'mod.empty': 'empty',
  'mod.choice.title': 'RESEARCH BREAKTHROUGH',
  'mod.choice.body': 'The lab assembled two prototypes. Unlock one module:',
  'mod.unlocked': 'Module unlocked: {name}',
  'bp.title': 'BLUEPRINT', 'bp.shop': 'BLUEPRINTS',
  'bp.toast': 'Blueprint received: {name}',
  'bp.built': 'A special node variant with randomized recipe stats.',
  'toast.modInstall': 'Module installed', 'toast.modRemove': 'Module removed: 50% refund',
  'toast.noSlots': 'No free slots',
  'dev.fast': 'DEV: time ×8', 'dev.normal': 'DEV: time ×1',
  'help.title': "OPERATOR'S GUIDE",
  'help.d1': 'LMB — select node, drag to move',
  'help.d2': 'Drag from an OUT port to an IN port — create a link',
  'help.d3': 'RMB — delete node or link, cancel placement',
  'help.d4': 'Wheel — zoom · WASD / middle button — camera',
  'help.m1': 'Finger on node — move · from a port — link',
  'help.m2': 'Finger on background — camera · pinch — zoom',
  'help.rule': 'ONE PORT = ONE LINK · OUTPUT → INPUT ONLY',
  'help.close': 'CLOSE',
  'menu.help': 'CONTROLS', 'menu.codex': 'CODEX', 'menu.reset': 'RESET NETWORK',
  'menu.confirm': 'SURE? RESET?', 'menu.grid': 'Grid', 'menu.zoomIn': 'Zoom in',
  'menu.zoomOut': 'Zoom out', 'menu.fit': 'Camera to start zone',
  'msg.place': 'Click the map to place · RMB / Esc — cancel',
  'toast.notEnough': 'Not enough resources',
  'toast.conn': 'Link established',
  'toast.errPort': 'Port is busy',
  'toast.errCompat': 'Incompatible resources',
  'toast.errSelf': 'Cannot link a node to itself',
  'toast.errDir': 'Links go OUTPUT → INPUT only',
  'toast.tech': 'Technology unlocked',
  'toast.saved': 'Saved',
  'toast.tutDone': 'Tutorial complete',
  'toast.nodeUpg': 'Node upgraded',
  'toast.upg': 'Upgrade purchased',
  'toast.reset': 'Network reset',
  'toast.core': 'NETWORK CORE ONLINE',
  'res.data': 'DATA', 'res.compute': 'COMPUTE', 'res.processed': 'PROCESSED',
  'res.filtered': 'FILTERED', 'res.encrypted': 'ENCRYPTED',
  'res.fragment': 'FRAGMENTS', 'res.credits': 'CREDITS', 'res.signal': 'SIGNAL',
  'resd.data': 'The raw flow of the network. Produced by relays, consumed by almost everything. Also the purchase currency (top bar).',
  'resd.signal': 'Raw signal from sensor arrays. Consumed only by analyzers.',
  'resd.compute': 'Compute power from server farms. Feeds processors, encryption and the data center.',
  'resd.processed': 'Proxy server output. An ingredient for the data center and refinery.',
  'resd.filtered': 'Firewall output. Needed for encryption and the refinery.',
  'resd.encrypted': 'Encryption core output. A data center ingredient.',
  'resd.fragment': 'Progress resource. Charges Network Core tiers — each tier speeds up production.',
  'resd.credits': 'Network currency. Buys advanced nodes, technologies and upgrades.',
  'nd.relay': 'RELAY SERVER', 'nd.relay.d': 'Generates DATA. The backbone of any network.',
  'nd.storage': 'DATA STORAGE', 'nd.storage.d': 'Banks DATA and converts it to your reserve (fuller = faster). Its DATA OUT feeds the buffer onward.',
  'nd.cache': 'DATA CACHE', 'nd.cache.d': 'A compact buffer between nodes: smooths the DATA flow.',
  'nd.compute': 'COMPUTE SERVER', 'nd.compute.d': 'Generates COMPUTE for processors.',
  'nd.router': 'ROUTER', 'nd.router.d': 'Splits DATA flow across two directions.',
  'nd.balancer': 'LOAD BALANCER', 'nd.balancer.d': 'Heavy distribution: up to 4 directions from 2 inputs.',
  'nd.proxy': 'PROXY SERVER', 'nd.proxy.d': 'Converts DATA into PROCESSED DATA.',
  'nd.processor': 'DATA PROCESSOR', 'nd.processor.d': 'Assembles FRAGMENTS from DATA and COMPUTE.',
  'nd.archive': 'ARCHIVE VAULT', 'nd.archive.d': 'Archives DATA directly into NETWORK CREDITS.',
  'nd.firewall': 'FIREWALL', 'nd.firewall.d': 'Filters DATA into FILTERED DATA.',
  'nd.encryption': 'ENCRYPTION CORE', 'nd.encryption.d': 'Produces ENCRYPTED DATA.',
  'nd.refinery': 'REFINERY', 'nd.refinery.d': 'Synthesizes FRAGMENTS from processed and filtered data.',
  'nd.datacenter': 'DATA CENTER', 'nd.datacenter.d': 'Monetizes your flow: produces NETWORK CREDITS.',
  'nd.hub': 'NETWORK HUB', 'nd.hub.d': 'Multi-port node for large backbones.',
  'nd.core': 'NETWORK CORE', 'nd.core.d': 'Heart of the infrastructure: DATA + COMPUTE into a heavy credit stream.',
  'nd.sensor': 'SENSOR ARRAY', 'nd.sensor.d': 'Harvests raw SIGNAL from the outside. Feeds analyzers.',
  'nd.signalbuffer': 'SIGNAL BUFFER', 'nd.signalbuffer.d': 'Banks SIGNAL and feeds it to analyzers.',
  'nd.analyzer': 'ANALYZER', 'nd.analyzer.d': 'Breaks down SIGNAL and COMPUTE into FRAGMENTS.',
  'nd.computebank': 'COMPUTE BANK', 'nd.computebank.d': 'Stores COMPUTE and feeds processing power to your processors.',
  'nd.smartrouter': 'SMART ROUTER', 'nd.smartrouter.d': 'Flexible junction: 3 inputs and 3 outputs for DATA.',
  'nd.compressor': 'COMPRESSOR', 'nd.compressor.d': 'Compresses PROCESSED and DATA into NETWORK CREDITS.',
  'nd.assembler': 'ASSEMBLER', 'nd.assembler.d': 'Assembles FRAGMENTS from ENCRYPTED and PROCESSED data.',
  'nd.forge': 'FORGE', 'nd.forge.d': 'Smelts ENCRYPTED data and COMPUTE into CREDITS.',
  'tc.routing': 'ADVANCED ROUTING', 'tc.routing.d': 'Unlocks Proxy Server, Load Balancer and Smart Router. The base for your path choice.',
  'tc.processing': 'DATA PROCESSING', 'tc.processing.d': 'Processing path: Data Processor, Archive Vault and Compute Bank.',
  'tc.telemetry': 'TELEMETRY', 'tc.telemetry.d': 'Raw-resource wave: Sensor Array, Signal Buffer and Analyzer.',
  'tc.security': 'SECURITY LAYER', 'tc.security.d': 'Security path: Firewall and Compressor.',
  'tc.encryptionTech': 'ENCRYPTION', 'tc.encryptionTech.d': 'Security path continues: Encryption Core and Assembler.',
  'tc.distributed': 'DISTRIBUTED COMPUTING', 'tc.distributed.d': 'Processing path apex: Data Center, Hub, Refinery and Forge.',
  'up.bandwidth': 'BANDWIDTH', 'up.bandwidth.d': '+50% throughput on all connections. Endless.',
  'up.storageCap': 'STORAGE CAPACITY', 'up.storageCap.d': '+50% capacity on data storages. Endless.',
  'up.prodSpeed': 'GENERATION SPEED', 'up.prodSpeed.d': 'Generators run 12% faster. Endless.',
  'up.procSpeed': 'PROCESSING SPEED', 'up.procSpeed.d': 'Processors run 12% faster. Endless.',
  'up.packetSize': 'PACKET SIZE', 'up.packetSize.d': 'Each packet carries +1 resource unit. Endless.',
  'start.tag': 'OPERATOR OF AN EXPERIMENTAL DIGITAL NETWORK',
  'start.desc': 'Place nodes, connect ports — the data flows will grow your grid into full-scale digital infrastructure.',
  'start.play': 'BOOT THE NETWORK',
  'start.continue': 'CONTINUE',
  'start.codex': 'OPEN CODEX',
  'start.tip': 'Autosave every 5 seconds · offline progress up to 8 hours',
  'start.chain': 'BASIC CHAIN',
  'start.controls': 'CONTROLS',
  'codex.title': "OPERATOR'S CODEX",
  'codex.tabNodes': 'NODES', 'codex.tabRes': 'RESOURCES', 'codex.tabLinks': 'LINKS', 'codex.tabFaq': 'FAQ',
  'codex.cat.generator': 'GENERATORS', 'codex.cat.storage': 'STORAGE',
  'codex.cat.transfer': 'ROUTING', 'codex.cat.processor': 'PROCESSING',
  'codex.in': 'IN', 'codex.out': 'OUT', 'codex.none': '—', 'codex.src': 'source',
  'codex.cycle': 'CYCLE', 'codex.buf': 'BUFFER', 'codex.sec': 's',
  'codex.basic': 'BASIC', 'codex.wallet': 'to reserve', 'codex.goal': 'to progress',
  'codex.linksTitle': 'HOW TO CONNECT NODES',
  'cx.r1': 'Links only go OUT port → IN port: hold an OUT port and drag onto an IN port.',
  'cx.r2': 'Port color is the resource. Only same-color ports can link.',
  'cx.r3': 'One port = one link. A filled square means the port is taken.',
  'cx.r4': 'Generators (relay, compute server) have no inputs — they are sources. Storage has both an input and an output.',
  'cx.r5': 'RMB on a line or node deletes it. On mobile — select the node and press DELETE.',
  'cx.bw': 'Every link has bandwidth (2 units/s by default). An amber line means saturation. Upgrade BANDWIDTH.',
  'codex.resTitle': 'TWO RESOURCE LAYERS',
  'codex.resBody': 'Colored resources flow through links between nodes. DATA and CREDITS also live in your global reserve (top bar) — purchases are paid from the reserve. FRAGMENTS charge Network Core tiers.',
  'faq.q1': 'Where do I start?',
  'faq.a1': 'The relay produces DATA → storage banks it and converts it to your reserve (that is your buying money). Save up DATA, buy a router and a compute server, then a processor — it assembles FRAGMENTS.',
  'faq.q2': 'Where does purchase money come from?',
  'faq.a2': 'Storage converts banked DATA into the global reserve — faster when fuller. Watch the “→ RESERVE” indicator on the storage card and the growth arrow under the DATA counter.',
  'faq.q3': 'How do I feed several nodes at once?',
  'faq.a3': 'Router: 1 input → 2 outputs. Load balancer: 2 inputs → 4 outputs. Storage and cache act as intermediate buffers with their own outputs.',
  'faq.q4': 'Why does my link fail?',
  'faq.a4': 'OUT → IN only; port colors must match; both ports free; no self-links. The reason appears right at the cursor.',
  'faq.q5': 'Where do FRAGMENTS come from?',
  'faq.a5': 'Data Processor: 2 DATA + 1 COMPUTE → 1 FRAGMENT. Later — the Refinery: processed + filtered data → fragment.',
  'faq.q6': 'How do I earn NETWORK CREDITS?',
  'faq.a6': 'Archive Vault (data → credits), Data Center (processed + encrypted + compute → credits), and the Network Core node.',
  'faq.q7': 'What do node statuses mean?',
  'faq.a7': 'ONLINE — working. NO INPUT — waiting for resources (broken-chain icon). FULL — nobody takes the output, connect the OUT port (overflow icon). IDLE — nothing to transfer.',
  'faq.q8': 'What is a DATA SURGE?',
  'faq.a8': 'A random generator occasionally glows amber for 8 seconds. Click it — it produces ×3 for 15 seconds. Miss it and it vanishes, no penalty.',
  'faq.q9': 'How do Network Core tiers work?',
  'faq.a9': 'Fragments charge the current tier (100 → 500 → 2500 …). Each cleared tier grants a permanent +10% production speed and a bigger core visual. Tiers never end.',
  'faq.q10': 'What are Network Reset and Legacy Points?',
  'faq.a10': 'After core tier 1, Network Reset wipes the run but grants permanent Legacy Points (√run credits ÷ 10) and +2% speed each. New runs cost more but scale bigger.',
  'faq.q11': 'Does the network run while I am away?',
  'faq.a11': 'Yes. On return, the game computes offline production (up to 8 hours at 50% efficiency) and offers a COLLECT window.',
  'faq.q12': 'How do I delete a node or link?',
  'faq.a12': 'RMB on the node or line (mobile: select the node → DELETE). A node’s links are removed with it. No refunds.',
};

const DICTS: Record<Lang, Record<string, string>> = { ru: RU, en: EN };

export function tr(lang: Lang, key: string, vars?: Record<string, string>): string {
  let s = DICTS[lang][key] ?? DICTS.en[key] ?? key;
  if (vars) {
    for (const k of Object.keys(vars)) s = s.split('{' + k + '}').join(vars[k]);
  }
  return s;
}

export function fmt(n: number): string {
  if (!isFinite(n)) return '0';
  if (n >= 1e9) return (n / 1e9).toFixed(2) + 'B';
  if (n >= 1e6) return (n / 1e6).toFixed(2) + 'M';
  if (n >= 1e4) return (n / 1e3).toFixed(1) + 'K';
  return String(Math.floor(n));
}

export function fmtRate(n: number): string {
  const a = Math.abs(n);
  if (a >= 100) return fmt(n);
  if (a >= 10) return (Math.round(n * 10) / 10).toString();
  return (Math.round(n * 100) / 100).toString();
}
